"""Export meeting notes to Markdown format.

File: backend/export/markdown.py
"""

from __future__ import annotations

import datetime
from typing import Optional

from backend.storage.models import Meeting, Summary, ActionItem, TranscriptSegmentDB


def meeting_to_markdown(
    meeting: Meeting,
    summary: Optional[Summary],
    action_items: list[ActionItem],
    segments: Optional[list[TranscriptSegmentDB]] = None,
    include_transcript: bool = False,
) -> str:
    """Render a complete meeting as a Markdown document."""
    lines = []

    # Header
    lines.append(f"# {meeting.title}")
    lines.append("")

    date_str = meeting.started_at.strftime("%d/%m/%Y %H:%M") if meeting.started_at else "N/A"
    duration_str = _format_duration(meeting.duration_seconds or 0)

    lines.append(f"**Ngày:** {date_str}  ")
    lines.append(f"**Thời lượng:** {duration_str}  ")
    lines.append(f"**Ngôn ngữ:** {meeting.primary_language}  ")
    lines.append(f"**ASR Engine:** {meeting.asr_post_engine or meeting.asr_live_engine or 'N/A'}  ")
    lines.append("")

    # Summary
    if summary:
        lines.append("---")
        lines.append("")
        lines.append(summary.content)
        lines.append("")

    # Action items table
    if action_items:
        lines.append("---")
        lines.append("")
        lines.append("## Công việc cần làm")
        lines.append("")
        lines.append("| # | Công việc | Phụ trách | Hạn | Trạng thái |")
        lines.append("|---|-----------|-----------|-----|------------|")
        for i, item in enumerate(action_items, 1):
            deadline = item.deadline or "—"
            owner = item.owner or "—"
            status = item.status or "open"
            lines.append(f"| {i} | {item.description} | {owner} | {deadline} | {status} |")
        lines.append("")

    # Transcript (optional)
    if include_transcript and segments:
        lines.append("---")
        lines.append("")
        lines.append("## Bản ghi chi tiết")
        lines.append("")
        for seg in sorted(segments, key=lambda s: s.start_time):
            speaker = seg.speaker_name or seg.speaker_label or "Unknown"
            start = _format_time(seg.start_time)
            lines.append(f"**[{start}] {speaker}:** {seg.text}")
            lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by MeetScribe — {datetime.datetime.now().strftime('%d/%m/%Y %H:%M')}*")

    return "\n".join(lines)


def _format_time(seconds: float) -> str:
    m = int(seconds // 60)
    s = int(seconds % 60)
    return f"{m:02d}:{s:02d}"


def _format_duration(seconds: int) -> str:
    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60
    if h:
        return f"{h}h {m}m"
    if m:
        return f"{m}m {s}s"
    return f"{s}s"
